language:
  java
script:
  - ant dist

secure: "ePgBswxgOKrA+WDSGFQCZk73PSfBSltb0W/TsdBcOyE8Nsyokpey2y1ntjKOy0VGUgPtjDFcmaLI7nyMk2FuegNWKsdLpIxhXVvFOY52yS7aZh2oIAjW/RsiP9FclgAy0qqPT/s5wXtfSM+egemn00YTTNn1P2mVnF0w883mfC8S3pEDPxanhSDa76JDyoOei9/LYkYzIzLaw/3yHqwrOLIPwXIfDsUzQZant9GyDYX0x8rEUxJErxruOYxcLR9KhZ7SydMnszcHxapL8aeJdX9xiRSl7tSlViHNHnLS+yjdx10MxG3UMUyy9GDXCWn7eCtNJ2k0L80mUnqTEZRHV1SkoglvTReFVQkfIGgu4IDb0IoyiDQSn80H03qCWntzLjJ5dK5Q1rfGjhjtU3xYWVq6qwlt49Zwdc0MCPOB41LMmSSQiowKrhRJSSEafqPhCeo0zGJoaFHva27DxeRbnnvFjeUK6cW1fJkwmSxfxDdt7+LynUQzox+TUIxpyac3MSokt6WqZH9HriGPKnZZE0ixQDDC0BMMvocv7jcsIEYBodfxhi5GeJTxvwdKiFCBnWzBxEI04SJ65Nau9plVe/FqGabqOuXxiXrusGwUVytdwUaK10p/wuxrbHb4YZVQtPC49eupMELcqW5x1DU4imGMASFZcOUHRlHb71LCftw="

